TYPO3:
  Neos:
    nodeTypes:
      groups:
        news:
          position: end
          label: News
    typoScript:
      autoInclude:
        Sfi.News: true
Sfi:
  News:
    newsList:
      numberOfItems: 10000
      pagination:
        itemsPerPage: 24
        maximumNumberOfLinks: 15
      sortProperty: date
      listTitle: 'СФИ сегодня'
      class: 'NewsList-Grid grid-block'
      archiveLink: ''
    newsLatest:
      numberOfItems: 6
      pagination: ~
      sortProperty: date
      listTitle: 'СФИ сегодня'
      class: 'NewsLatest-Grid grid-block'
      wrapClass: 'NewsLatest'
      archiveLink: '~/sfi-today'
    newsRelated:
      numberOfItems: 4
      sortProperty: date
      listTitle: ''
      class: ''
      archiveLink: '~/sfi-today'
      thumbnailWidth: 100
      thumbnailHeight: 100
      dateFormat: 'j F Y'
    newsShort:
      thumbnailWidth: 420
      thumbnailHeight: 222
      dateFormat: 'j F Y'
    newsDetail:
      dateFormat: 'j F Y'
    announcementsList:
      numberOfItems: 6
      pagination: ~
      sortProperty: date
      listTitle: ''
      class: ''
      archiveLink: ''
    announcementShort:
      thumbnailWidth: 420
      thumbnailHeight: 222
      dateFormat: ''
    announcementDetail:
      dateFormat: 'j F Y G:i'
    topList:
      numberOfItems: 3
      sortProperty: date
      listTitle: ~
      class: 'Carousel--Cover js-carousel-1x'
      archiveLink: ''
    topShort:
      thumbnailWidth: 1440
      thumbnailHeight: 700
      dateFormat: d.m
    rssList:
      numberOfItems: 50
      sortProperty: date