TYPO3:
  Neos:
    nodeTypes:
      groups:
        news:
          position: end
          label: News
    typoScript:
      autoInclude:
        Sfi.News: true
Sfi:
  News:
    newsList:
      numberOfItems: 28
      pagination:
        itemsPerPage: 10
        maximumNumberOfLinks: 15
      sortProperty: date
      listTitle: 'Все материалы'
      class: 'medium-block-grid-4 large-block-grid-4'
    newsLatest:
      numberOfItems: 4
      pagination:
        itemsPerPage: 10
        maximumNumberOfLinks: 15
      sortProperty: date
      listTitle: 'СФИ сегодня'
      class: 'medium-block-grid-4 large-block-grid-4'
    newsRelated:
      numberOfItems: 5
      sortProperty: date
      listTitle: 'Новости СФИ'
      class: ''
    newsShort:
      thumbnailWidth: 420
      thumbnailHeight: 222
      dateFormat: 'F jS'
    newsDetail:
      dateFormat: 'F jS, Y'
    announcementsList:
      numberOfItems: 6
      pagination:
        itemsPerPage: 10
        maximumNumberOfLinks: 15
      sortProperty: date
      listTitle: 'Анонсы'
      class: ''
    announcementShort:
      thumbnailWidth: 420
      thumbnailHeight: 222
      dateFormat: 'F jS, Y G:i'
    announcementDetail:
      dateFormat: 'F jS, Y'
    topList:
      numberOfItems: 4
      sortProperty: date
      listTitle: ~
      class: 'Carousel js-carousel-1x'
    topShort:
      thumbnailWidth: 1200
      thumbnailHeight: 600
      dateFormat: d.m
