TYPO3:
  Neos:
    nodeTypes:
      groups:
        news:
          position: end
          label: News
    typoScript:
      autoInclude:
        Sfi.News: true
Sfi:
  News:
    newsList:
      numberOfItems: 6
      pagination:
        itemsPerPage: 10
        maximumNumberOfLinks: 15
      sortProperty: date
      sortOrder: DESC
      listTitle: 'СФИ сегодня'
      class: 'medium-block-grid-2 large-block-grid-3'
    newsShort:
      thumbnailWidth: 420
      thumbnailHeight: 222
      dateFormat: d.m
    newsDetail:
      dateFormat: 'F jS, Y'
    announcementsList:
      numberOfItems: 6
      pagination:
        itemsPerPage: 10
        maximumNumberOfLinks: 15
      sortProperty: date
      sortOrder: DESC
      listTitle: 'Анонсы'
      class: 'medium-block-grid-2 large-block-grid-3'
    announcementShort:
      thumbnailWidth: 420
      thumbnailHeight: 222
      dateFormat: d.m
    announcementDetail:
      dateFormat: 'F jS, Y'
    topList:
      numberOfItems: 4
      sortProperty: date
      sortOrder: DESC
      listTitle: ~
      class: ''
    topShort:
      thumbnailWidth: 1200
      thumbnailHeight: 600
      dateFormat: d.m
